Repository openfun/richie-site-factory, pull requests merged in 2019-07, with the labels that each got.

#21 ⬆️(core) upgrade to Richie 1.5.0
  CHANGELOG.md
  requirements/base.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: improvement, needs review

#22 🔖(chore) bump release to 0.3.0
  CHANGELOG.md
  src/backend/funmooc/__init__.py
  src/frontend/package.json
Labels: needs review, release

#24 💩(permissions) disable unsorted uploads from Django filer
  CHANGELOG.md
  src/backend/funmooc/core/admin.py
Labels: critical, improvement, needs review
