Repository openfun/richie-site-factory, pull requests merged in 2019-04, with the labels that each got.

#3 🐛(settings) fix settings following changes on Richie master
  Makefile
  src/backend/funmooc/settings.py
Labels: bug, easy pick

#7 💄(layout) customize platform logo
  src/backend/funmooc/static/images/logo.png
Labels: improvement, needs review

#10 🐛(circleci) fix hub publication job
  .circleci/config.yml
Labels: bug, needs review
