Repository openfun/richie-site-factory, pull requests merged in 2020-11, with the labels that each got.

#154 Add media files expiration lifecyle rule for demo site
  aws/s3.tf
  aws/variables.tf
  sites/demo/CHANGELOG.md
  sites/demo/aws/config.tfvars
Labels: improvement

#155 🚸(funcampus) clarify the "contact us" call-to-action
  .circleci/config.yml
  sites/funcampus/CHANGELOG.md
  sites/funcampus/src/backend/locale/fr/LC_MESSAGES/django.po
  sites/funcampus/src/backend/templates/courses/cms/course_detail.html
Labels: improvement

#162 🚨(bin/release) should_commit does not work on Mac OS
  .circleci/config.yml
  bin/release
Labels: bug

#166 ⬆️(all) unpin django to 3.1.1
  .circleci/config.yml
  sites/cnfpt/CHANGELOG.md
  sites/cnfpt/requirements/base.txt
  sites/demo/CHANGELOG.md
  sites/demo/requirements/base.txt
  sites/demo/src/frontend/yarn.lock
  sites/funcampus/CHANGELOG.md
  sites/funcampus/requirements/base.txt
  sites/funcorporate/CHANGELOG.md
  sites/funcorporate/requirements/base.txt
  sites/funcorporate/src/frontend/yarn.lock
  sites/funmooc/CHANGELOG.md
  sites/funmooc/requirements/base.txt
  sites/funmooc/src/frontend/yarn.lock
Labels: dependencies
