Repository openfun/richie-site-factory, pull requests merged in 2020-09, with the labels that each got.

#111 LMS bridge for the Demo website
  .circleci/config.yml
  sites/demo/CHANGELOG.md
  sites/demo/src/backend/demo/__init__.py
  sites/demo/src/frontend/package.json
Labels: bug

#112 Feat/funcorporate zendesk
  .circleci/config.yml
  sites/funcorporate/CHANGELOG.md
  sites/funcorporate/src/backend/locale/en/LC_MESSAGES/django.po
  sites/funcorporate/src/backend/locale/fr/LC_MESSAGES/django.po
  sites/funcorporate/src/backend/templates/richie/base.html
Labels: feature

#119 💄(funcorporate) fix course category badge layout
  .circleci/config.yml
  sites/funcorporate/CHANGELOG.md
  sites/funcorporate/src/frontend/scss/_main.scss
  sites/funcorporate/src/frontend/scss/components/_subheader.scss
  sites/funcorporate/src/frontend/scss/settings/_colors.scss
Labels: improvement

#122 ✨(demo) force user.is_superuser on login when they have is_staff True
  .circleci/config.yml
  sites/demo/CHANGELOG.md
  sites/demo/src/backend/demo/settings.py
  sites/demo/src/backend/demo/social/pipeline/__init__.py
  sites/demo/src/backend/demo/social/pipeline/user.py
Labels: improvement

#131 🏗(funcampus) move cms site to www.fun-campus.fr
  .circleci/config.yml
  sites/funcampus/aws/config.tfvars
Labels: improvement
