Repository openfun/richie-site-factory, pull requests merged in 2020-07, with the labels that each got.

#81 ✨(dockercompose) allow switching site without losing data
  .circleci/config.yml
  Makefile
  docker-compose.yml
Labels: feature

#78 🐛(Makefile) fix resetting data folder when absent
  Makefile
Labels: bug

#82 🐛(Makefile) fix database directory initialization
  .circleci/config.yml
  Makefile
Labels: bug, needs review

#86 ✨(funcampus) add a new funcampus site for the future fun-campus.fr
  .circleci/config.yml
  sites/funcampus/CHANGELOG.md
  sites/funcampus/aws/config.tfvars
  sites/funcampus/requirements/base.txt
  sites/funcampus/requirements/dev.txt
  sites/funcampus/src/backend/__init__.py
  sites/funcampus/src/backend/base/__init__.py
  sites/funcampus/src/backend/base/admin.py
  sites/funcampus/src/backend/base/fixtures/category_logo/logo1.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo10.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo11.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo12.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo13.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo14.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo2.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo3.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo4.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo5.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo6.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo7.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo8.png
  sites/funcampus/src/backend/base/fixtures/category_logo/logo9.png
  sites/funcampus/src/backend/base/static/richie/css/.keep
  sites/funcampus/src/backend/base/static/richie/favicon/android-chrome-192x192.png
  sites/funcampus/src/backend/base/static/richie/favicon/android-chrome-512x512.png
  sites/funcampus/src/backend/base/static/richie/favicon/apple-touch-icon.png
  sites/funcampus/src/backend/base/static/richie/favicon/browserconfig.xml
  sites/funcampus/src/backend/base/static/richie/favicon/favicon-16x16.png
  sites/funcampus/src/backend/base/static/richie/favicon/favicon-32x32.png
  sites/funcampus/src/backend/base/static/richie/favicon/favicon.ico
  sites/funcampus/src/backend/base/static/richie/favicon/mstile-150x150.png
  sites/funcampus/src/backend/base/static/richie/favicon/safari-pinned-tab.svg
  sites/funcampus/src/backend/base/static/richie/favicon/site.webmanifest
  sites/funcampus/src/backend/base/static/richie/images/logo-alt.png
  sites/funcampus/src/backend/base/static/richie/images/logo.png
  sites/funcampus/src/backend/base/storage.py
  sites/funcampus/src/backend/base/tests/__init__.py
  sites/funcampus/src/backend/base/tests/test_settings.py
  sites/funcampus/src/backend/funcampus/__init__.py
  sites/funcampus/src/backend/funcampus/settings.py
  sites/funcampus/src/backend/funcampus/urls.py
  sites/funcampus/src/backend/funcampus/wsgi.py
  sites/funcampus/src/backend/manage.py
  sites/funcampus/src/backend/setup.cfg
  sites/funcampus/src/backend/templates/courses/cms/course_detail.html
  sites/funcampus/src/backend/templates/richie/base.html
  sites/funcampus/src/frontend/package.json
  sites/funcampus/src/frontend/scss/_main.scss
  sites/funcampus/src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  sites/funcampus/src/frontend/scss/settings/_colors.scss
  sites/funcampus/src/frontend/scss/settings/_variables.scss
  sites/funcampus/src/frontend/yarn.lock
Labels: FUN, feature
