Repository openfun/richie-site-factory, pull requests merged in 2020-05, with the labels that each got.

#52 💄(layout) set layout theme
  CHANGELOG.md
  requirements/base.txt
  src/backend/funmooc/fixtures/icons/academic.png
  src/backend/funmooc/fixtures/icons/accessible.png
  src/backend/funmooc/fixtures/icons/cc.png
  src/backend/funmooc/fixtures/icons/certificate.png
  src/backend/funmooc/fixtures/icons/subtitles.png
  src/backend/funmooc/gimporter/import_scripts/courses.py
  src/backend/funmooc/settings.py
  src/backend/funmooc/static/richie/favicon/android-chrome-192x192.png
  src/backend/funmooc/static/richie/favicon/android-chrome-512x512.png
  src/backend/funmooc/static/richie/favicon/apple-touch-icon.png
  src/backend/funmooc/static/richie/favicon/browserconfig.xml
  src/backend/funmooc/static/richie/favicon/favicon-16x16.png
  src/backend/funmooc/static/richie/favicon/favicon-32x32.png
  src/backend/funmooc/static/richie/favicon/favicon.ico
  src/backend/funmooc/static/richie/favicon/mstile-150x150.png
  src/backend/funmooc/static/richie/favicon/safari-pinned-tab.svg
  src/backend/funmooc/static/richie/favicon/site.webmanifest
  src/backend/funmooc/static/richie/images/logo-white.png
  src/backend/funmooc/static/richie/images/logo.png
  src/backend/funmooc/templates/richie/base.html
  src/backend/funmooc/templates/richie/section/section_quaternary.html
  src/backend/funmooc/templates/richie/section/section_quinary.html
  src/backend/funmooc/urls.py
  src/frontend/scss/_main.scss
  src/frontend/scss/components/templates/richie/section/_section.scss
  src/frontend/scss/settings/_colors.scss
  src/frontend/scss/settings/_variables.scss
Labels: improvement

#53 ⬆️(project) upgrade to richie 2.0.0-beta.5
  CHANGELOG.md
  requirements/base.txt
  src/backend/funmooc/settings.py
  src/backend/funmooc/static/richie/images/logo-alt.png
  src/frontend/package.json
  src/frontend/scss/settings/_colors.scss
  src/frontend/scss/settings/_variables.scss
  src/frontend/yarn.lock
Labels: improvement

#54 🔖(chore) bump release to 0.9.0
  CHANGELOG.md
  src/backend/funmooc/__init__.py
  src/frontend/package.json
Labels: release

#57 💄(large_banner) adjust image background size for hero-intro variant
  CHANGELOG.md
  src/frontend/scss/_main.scss
  src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
  src/frontend/scss/settings/_colors.scss
Labels: improvement

#63 🔖(chore) bump release to 0.10.0
  CHANGELOG.md
  src/backend/funmooc/__init__.py
  src/frontend/package.json
Labels: bug, improvement
