Repository openfun/richie-site-factory, pull requests merged in 2021-03, with the labels that each got.

#201 ✨(funmooc) add labels categories as search filter
  .circleci/config.yml
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/backend/funmooc/settings.py
  sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
Labels: FUN, feature

#205 ✨(funmooc) display first open course run in course detail top header
  .circleci/config.yml
  .circleci/src/jobs/@backend.yml
  Makefile
  sites/funmooc/CHANGELOG.md
  sites/funmooc/requirements/dev.txt
  sites/funmooc/src/backend/base/tests/test_templates.py
  sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
  sites/funmooc/src/backend/templates/courses/cms/course_detail.html
  sites/funmooc/src/frontend/scss/_main.scss
  sites/funmooc/src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Labels: improvement

#207 🐛(styles) import missing stylesheet for LTI consumer plugin
  .circleci/config.yml
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/frontend/scss/_main.scss
Labels: bug

#208 🐛(all) import missing stylesheet for LTI consumer plugin
  .circleci/config.yml
  sites/cnfpt/CHANGELOG.md
  sites/cnfpt/src/frontend/scss/_main.scss
  sites/demo/CHANGELOG.md
  sites/demo/src/frontend/scss/_main.scss
  sites/funcampus/CHANGELOG.md
  sites/funcampus/src/frontend/scss/_main.scss
  sites/funcorporate/CHANGELOG.md
  sites/funcorporate/src/frontend/scss/_main.scss
Labels: bug

#210 🚸(search) rename "first session" filter to "new course"
  .circleci/config.yml
  sites/funmooc/CHANGELOG.md
  sites/funmooc/src/backend/funmooc/settings.py
  sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
Labels: improvement

#211 🔧(funcampus) update cloudfront distribution destination
  .circleci/config.yml
  sites/funcampus/aws/config.tfvars
Labels: improvement, needs review

#213 🔧(funcorporate) update cloudfront distribution destination
  .circleci/config.yml
  sites/funcorporate/aws/config.tfvars
Labels: improvement
